#!/usr/bin/env bash
set -euo pipefail

tool="${IA_TOOL:-claude}"

case "$tool" in
    claude) dir="$HOME/.claude"; rtk_md="$dir/rules/rtk.md" ;;
    codex) dir="$HOME/.codex"; rtk_md="$dir/RTK.md" ;;
    copilot) dir="$HOME/.copilot"; rtk_md="$dir/instructions/rtk.instructions.md" ;;
    *) exec "$tool" "$@" ;;
esac

# The global CLAUDE.md, AGENTS.md and copilot-instructions.md link to directives
# shared by every agent, and rtk init appends to them: run it in a scratch HOME.
rtk_init_claude() {
    local scratch="$1"
    HOME="$scratch" rtk init -g --no-patch &&
        install -D -m 600 "$scratch/.claude/RTK.md" "$rtk_md" &&
        rtk init -g --hook-only --auto-patch
}

rtk_init_codex() {
    local scratch="$1"
    if [ -e "$dir/hooks.json" ]; then
        cp "$dir/hooks.json" "$scratch/.codex/"
    fi
    HOME="$scratch" rtk init -g --codex &&
        cp "$scratch/.codex/RTK.md" "$scratch/.codex/hooks.json" "$dir/"
}

render_codex_instructions() {
    local override="$dir/AGENTS.override.md"
    local marker='<!-- Generated by ia-entrypoint from AGENTS.md and RTK.md. -->'
    local temp

    if [ -L "$override" ]; then
        echo "Codex instructions not updated: $override is a symlink" >&2
        return 1
    fi
    if [ -e "$override" ] &&
        [ "$(sed -n '1p' "$override")" != "$marker" ]; then
        echo "Codex instructions not updated: $override is not managed by ia-entrypoint" >&2
        return 1
    fi

    temp="$(mktemp "$dir/.AGENTS.override.md.XXXXXX")" || return 1
    if ! {
        printf '%s\n' "$marker" >"$temp" &&
            cat "$dir/AGENTS.md" >>"$temp" &&
            printf '\n' >>"$temp" &&
            cat "$rtk_md" >>"$temp"
    }; then
        rm -- "$temp"
        return 1
    fi

    if [ -e "$override" ] && cmp -s "$temp" "$override"; then
        rm -- "$temp"
    else
        mv -- "$temp" "$override"
    fi
}

rtk_init_copilot() {
    local scratch="$1"
    HOME="$scratch" rtk init -g --copilot &&
        install -D -m 600 "$scratch/.copilot/copilot-instructions.md" "$rtk_md" &&
        install -D -m 600 "$scratch/.copilot/hooks/rtk-rewrite.json" "$dir/hooks/rtk-rewrite.json"
}

rtk_init() {
    local scratch rc=0
    scratch="$(mktemp -d)"
    mkdir "$scratch/.$tool"
    "rtk_init_$tool" "$scratch" || rc=$?
    rm -rf -- "$scratch"
    return "$rc"
}

ensure_claude_skill_links() {
    local skills_dir="$HOME/.claude/skills"
    local skill target link existing_target

    mkdir -p "$skills_dir"
    for skill in grill-me grilling; do
        target="$HOME/.agents/skills/$skill"
        link="$skills_dir/$skill"

        if [ -L "$link" ]; then
            existing_target="$(readlink -f "$link" 2>/dev/null || true)"
            [ "$existing_target" = "$target" ] && continue
        fi

        if [ -e "$link" ] || [ -L "$link" ]; then
            echo "IA skill link not created: $link already exists" >&2
        else
            ln -s "$target" "$link"
        fi
    done
}

if [ "$tool" = claude ]; then
    ensure_claude_skill_links
fi

# Each tool's config dir is bind-mounted from the host (see ia.sh) and persists
# across containers. Regenerate rtk's global config only when its instructions
# file is missing or the image's rtk version changed since it was last written,
# so a rebuilt image refreshes it without paying the cost on every start. Run it
# non-interactively and never let a failure block the agent from launching.
stamp="$dir/.rtk-version"
version="$(rtk --version 2>/dev/null || true)"
prev=""
[ -e "$stamp" ] && prev="$(<"$stamp")"

if [ ! -e "$rtk_md" ] || [ "$prev" != "$version" ]; then
    if rtk_init </dev/null >/dev/null; then
        printf '%s\n' "$version" >"$stamp"
    else
        echo "rtk init failed; continuing" >&2
    fi
fi

if [ "$tool" = codex ] && [ -f "$rtk_md" ]; then
    if ! render_codex_instructions; then
        echo "Codex instruction rendering failed; continuing" >&2
    fi
fi

exec "$tool" "$@"
